### ISSUE TITLE
Add more possibilities of incorrect induction

### ISSUE THREAD

**Issue by lfaucon** [vood00child/tama#1]
The virtual student should have more possibility to make mistakes while learning, that the teacher (player) should be careful about. 
- Coloring examples and counter examples
- Rotating examples and counter examples
- Adding Squares/Rhombus/Rectangles
- Adding thin of thick parallelograms

**Comment by lfaucon** [comment]
#10 covers most of this issue.

```
      hasThreeEdges: false,
      hasFourEdges: true,
      hasFiveEdges: false,
      hasSixEdges: false,
      hasSameLengthEdges: false,
      hasSameLengthEveryPairOppositeEdges: true,
      hasSameLengthOnePairOppositeEdges: true,
      hasEveryPairOppositeEdgesParallel: true,
      hasOnePairOppositeEdgesParallel: true,
      isRed: false,
      isGreen: false,
      isBlue: true
```

To cover the rest, I suggest:
- adding the two useless features `isRotated` and `isThin` 
- adding `hasAtleastOneRightAngle` and `hasEveryRightAngles`

**Comment by vood00child** [comment]
#14 covers this issue
